from __future__ import annotations

import argparse
import logging
from pathlib import Path


LOGGER = logging.getLogger("project_guard")


DEFAULT_DIRS = [
    "src",
    "scratch",
    "docs",
    "experiments",
    "experiments/_archive",
]


def _configure_logging() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")


def ensure_dirs(project_root: Path) -> list[Path]:
    created: list[Path] = []
    for rel in DEFAULT_DIRS:
        p = project_root / rel
        if p.exists():
            continue
        p.mkdir(parents=True, exist_ok=True)
        created.append(p)
    return created


def ensure_gitignore(project_root: Path) -> bool:
    """
    Non-destructive:
    - If .gitignore missing: create minimal one
    - If exists: append missing patterns once
    """
    gi = project_root / ".gitignore"
    baseline = [
        "# --- generated by /home/sqr/_meta/project_guard.py ---",
        "__pycache__/",
        "*.pyc",
        ".pytest_cache/",
        ".ruff_cache/",
        ".mypy_cache/",
        ".ipynb_checkpoints/",
        ".DS_Store",
        "scratch/**/outputs/",
        "scratch/**/tmp/",
        "experiments/**/logs/",
        "experiments/**/results/*.parquet",
        "experiments/**/results/*.pkl",
        "experiments/**/results/*.db",
        "",
    ]

    if not gi.exists():
        gi.write_text("\n".join(baseline) + "\n", encoding="utf-8")
        return True

    existing = gi.read_text(encoding="utf-8").splitlines()
    existing_set = set(line.strip() for line in existing if line.strip())
    to_add = [line for line in baseline if line.strip() and line.strip() not in existing_set]
    if not to_add:
        return False

    with gi.open("a", encoding="utf-8") as f:
        f.write("\n")
        f.write("\n".join(to_add))
        f.write("\n")
    return True


def ensure_experiment_readme_stub(project_root: Path) -> bool:
    exp_readme = project_root / "experiments" / "README.md"
    if exp_readme.exists():
        return False
    content = "\n".join(
        [
            "# Experiments",
            "",
            "## Rule",
            "- Every experiment lives in its own folder: `YYYY-MM-DD_short_desc/`",
            "- Phase 1 first (single-effect), then Phase 2 (joint) after Phase 1 completes",
            "- Always write artifacts to `results/` (trades/positions/nav/metrics/reconciliation)",
            "",
            "## Quick Start",
            "1) Create experiment folder",
            "2) Write `README.md` (hypothesis, isolated variable, baseline, expected signal, failure condition)",
            "3) Run backtest",
            "4) Run preflight: `/home/sqr/_meta/preflight_backtest.py <experiment_dir>`",
            "",
        ]
    )
    exp_readme.write_text(content + "\n", encoding="utf-8")
    return True


def main() -> int:
    _configure_logging()
    parser = argparse.ArgumentParser(description="Non-destructive project hygiene + structure guard.")
    parser.add_argument("project_root", type=Path, help="Absolute path to project root")
    args = parser.parse_args()

    root = args.project_root.expanduser().resolve()
    if not root.exists() or not root.is_dir():
        LOGGER.error("Invalid project root: %s", root)
        return 1

    created_dirs = ensure_dirs(root)
    for p in created_dirs:
        LOGGER.info("Created dir: %s", p)
    if not created_dirs:
        LOGGER.info("Dirs: no changes needed.")

    if ensure_gitignore(root):
        LOGGER.info("Updated .gitignore")
    else:
        LOGGER.info(".gitignore: no changes needed.")

    if ensure_experiment_readme_stub(root):
        LOGGER.info("Created experiments/README.md")
    else:
        LOGGER.info("experiments/README.md: exists.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())


